import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api, RouterOutputs } from "~/utils/api";

import { UserButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return <div className="flex w-full gap-3 border-b border-slate-400">
    <UserButton />
    <input placeholder="Type some emojis!" className="grow bg-transparent outline-none" />
  </div>
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <Image src={author.profileImageUrl} 
      className="h-14 w-14 rounded-full"
      alt={`@${author.username}'s profile picture`}
      width={56}
      height={56}/>
      <div className="flex flex-col">
        <div className="flex text-slate-300 gap-1">
          <span>{`@${author.username!}`}</span>
          <span className="font-thin">{` · ${dayjs(post.createdAt).fromNow()}`}</span>  
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};


const Home: NextPage = () => {
  const {data, isLoading} = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>No posts so far :/</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x h-full border-slate-400">
          <CreatePostWizard/>
          <div>
            <div className="text-2xl text-white flex flex-col">
              {[...data]?.map((fullPost) => 
              (<PostView {...fullPost} key={fullPost.post.id} />))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
